# See http://docs.fluentd.org/v0.12/articles/before-install
# Should restart for changes to take effect
- name: increase file descriptor limits
  blockinfile:
    dest: /etc/security/limits.conf
    block: |
      root soft nofile 65536
      root hard nofile 65536
      * soft nofile 65536
      * hard nofile 65536

# Not sure if necessary, the default Ubuntu timesyncd seems to do the same
- name: install ntpd
  apt: name=ntp state=present

- name: add td-agent user to adm group to give it access to nginx logs
  become_user: root
  shell: usermod --groups adm td-agent

- name: add sql extensions to fluent
  gem: name="{{item}}" state=present executable=/usr/sbin/td-agent-gem
  with_items:
    - fluent-plugin-sql
    - pg

# TODO: Check if exists
#- name: make analytics db tables
#  become_user: atuser
#  shell: psql -d atsite -c "{{lookup('template', 'create-analytics-tables.psql')}}"
