- name: store crossbar authentication ticket for services, *before* starting crossbar
  lineinfile:
    dest: /etc/environment
    # Generates new password when not exists
    line: "AT_CROSSBAR_TICKET={{lookup('password', 'passwdlookup/crossbar-ticket-passwd.txt')}}"

- name: install crossbar in virtualenv
  become_user: "{{USER}}"
  pip:
    name: crossbar
    virtualenv: "{{USER_ROOT}}/crossbar-venv"
    virtualenv_python: python3.6

- name: make crossbar config folder
  file:
    # Writes pid to this folder so must be accessible by user crossbar runs as
    owner: atuser
    group: atuser
    path: /home/atuser/.crossbar
    state: directory

- name: configure crossbar node
  template:
    src: config.yaml
    dest: /home/atuser/.crossbar/config.yaml
