- name: set default locale
  lineinfile:
    dest: /etc/environment
    line: "LC_ALL=C.UTF-8"

- name: set media root for services and tasks
  # Subfolder convention is: /video /audio /image
  lineinfile:
    dest: /etc/environment
    line: 'AT_MEDIA_ROOT="{{USER_ROOT}}/media"'

- name: make media and log dirs
  file:
    path: "{{item}}"
    owner: "{{USER}}"
    group: "{{USER}}"
    state: directory
    # Default mode is 775, but just to make sure
    mode: 0775
  with_items:
    - "{{USER_ROOT}}/media/video"
    - "{{USER_ROOT}}/media/image"
    - "{{USER_ROOT}}/media/audio"
    - "{{USER_ROOT}}/log"

- name: add python 3.6 repo
  apt_repository:
    repo: ppa:jonathonf/python-3.6

- name: install packages
  tags: ["apt"]
  apt: name={{item}} state=present update_cache=yes
  with_items:
    # Latest Python
    - python3.6
    # Nice for debugging etc.
    - ipython
    # Needed for setting up virtualenv and building libraries
    - python3.6-dev
    - python3-pip
    - virtualenv
    - gcc
    # Monitor system resources
    - htop
    # Process watcher
    - supervisor
    # Reverse proxy and more
    - nginx
    # Postgres and PostGIS geospatial extention
    - postgresql
    - postgresql-9.5-postgis-2.2
    - "*postgis-scripts"
    - libpq-dev
    # Used by ansible postgres module
    - python-psycopg2
    # Convert video, audio
    - ffmpeg

- name: make virtualenv and install python3 dependencies
  become_user: "{{USER}}"
  pip:
    name: "{{item}}"
    virtualenv: "{{USER_ROOT}}/venv"
    virtualenv_python: python3.6
  with_items:
    - pytest
    - autobahn
    - aiohttp
    - cchardet
    - aiodns
    - aiohttp_jinja2
    - asyncpg
    - psycopg2
    - sqlalchemy
    - pillow
    - python-dateutil
    - hashids
    - python-telegram-bot
    - pygal
    - jsonschema
    # Sentry client
    - raven
