- name: set default locale
  lineinfile:
    dest: /etc/environment
    line: "LC_ALL=C.UTF-8"

- name: add python 3.6 repo
  apt_repository:
    repo: ppa:jonathonf/python-3.6

- name: install packages
  tags: ["apt"]
  apt: name={{item}} state=present update_cache=yes
  with_items:
    # Latest Python
    - python3.6
    # Needed for setting up virtualenv and building libraries
    - python3.6-dev
    - python3-pip
    - virtualenv
    - gcc
    # Monitor system resources
    - htop
    # Process watcher
    - supervisor
    # Reverse proxy and more
    - nginx
    # Postgres and PostGIS geospatial extention
    - postgresql
    - libpq-dev
    - postgis
    - "*postgis-scripts"
    # Used by ansible postgres module
    - python-psycopg2
    # Convert video, audio
    - ffmpeg

- name: make virtualenv and install python3 dependencies
  become_user: "{{USER}}"
  pip:
    name: "{{item}}"
    virtualenv: "{{USER_ROOT}}/venv"
    virtualenv_python: python3.6
  with_items:
    - pytest
    - autobahn
    - aiohttp
    - cchardet
    - aiodns
    - aiohttp_jinja2
    - asyncpg
    - psycopg2
    - sqlalchemy
    - pillow
