- name: make new postgres db
  become_user: postgres
  postgresql_db:
    name: "{{dbname}}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'

- name: make new postgres user
  become_user: postgres
  postgresql_user:
    db: "{{dbname}}"
    name: "{{USER}}"
    password: "{{PASSWORD}}"

- name: add postgis to db
  become_user: postgres
  postgresql_ext: name=postgis db={{dbname}}

- name: put database url in environment file for easy cmdline use
  lineinfile:
    dest: /etc/environment
    line: 'DB_URI_{{dbname|upper}}="postgresql://{{USER}}:{{PASSWORD}}@localhost/{{dbname|lower}}"'
