version: 2
controller: {}
workers:
- type: router
  realms:
  - name: realm1
    roles:
    - name: backend
      permissions:
      - uri: ''
        match: prefix
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
        disclose:
          caller: false
          publisher: false
        cache: true
    - name: frontend
      permissions:
      - uri: 'at.public.'
        match: prefix
        allow:
          call: true
          register: false
          publish: false
          subscribe: true
        disclose:
          caller: true
          publisher: false
        cache: true
  transports:
  - type: web
    endpoint:
      type: tcp
      port: 8080
    paths:
      ws:
        type: websocket
        auth:
          anonymous:
            type: static
            role: frontend
          ticket:
            type: static
            principals:
              backend:
                ticket: "${AT_CROSSBAR_TICKET}"
                role: backend
