---
- hosts: adventure-track
  remote_user: root
  become: true
  become_method: sudo
  vars:
    # User specifically created for running this app
    USER: atuser
    PASSWORD: "{{lookup('password', 'passwdlookup/atuser-password.txt')}}"
    DEV: false
    USER_ROOT: /home/{{USER}}
    REPO_ROOT: "{{USER_ROOT}}/adventure-track"

  pre_tasks:
    - name: clone git repo
      git:
        repo: 'https://github.com/the-fonz/adventure-track'
        dest: "{{REPO_ROOT}}"
        update: yes

  roles:
    - add_user
    - common
    - role: crossbar
      tags: ["crossbar"]
    - role: postgres
      dbname: atsite
      tags: ["postgres"]
    - supervisord
    - role: nginx
      tags: ["nginx"]
    - firewall
