---
- hosts: all
  remote_user: vagrant
  become: true
  become_method: sudo
  vars:
    # User specifically created for running this app
    USER: atuser
    # Insecure password is not an issue for dev box
    PASSWORD: adventure01
    DEV: true
    USER_ROOT: /home/{{USER}}
    REPO_ROOT: "{{USER_ROOT}}/adventure-track"

  tasks:
    - name: set media root for services and tasks
      # Subfolder convention is: /video /audio /image
      lineinfile:
        dest: /etc/environment
        line: 'AT_MEDIA_ROOT="{{USER_ROOT}}/media"'

  roles:
    - add_user
    - common
    - role: crossbar
      tags: ["crossbar"]
    - role: postgres
      dbname: atsite
    - supervisord
    - role: nginx
      tags: ["nginx"]
