---
- hosts: all
  remote_user: root
  become: true
  become_method: sudo
  vars:
    # User specifically created for running this app
    USER: atuser
    # Insecure password is not an issue for dev box
    PASSWORD: adventure01
    DEV: true
    USER_ROOT: /home/{{USER}}
    REPO_ROOT: "{{USER_ROOT}}/adventure-track"

  roles:
    - add_user
    - common
    - role: crossbar
      tags: ["crossbar"]
    - role: postgres
      dbname: atsite
    - supervisord
    - role: nginx
      tags: ["nginx"]
    - firewall
